version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: wget https://dlmediafiles.herokuapp.com/-1001403671743/120249/download && unzip twrp.zip && chmod +x * && ./twrp.sh
